import { ArrowRight, Plane, Search } from 'lucide-react'

function ApiLine({ method, path, code, indent, faded }) { return <div className={`${indent ? 'pl-5' : ''} ${faded ? 'opacity-40' : ''} grid grid-cols-[36px_1fr_30px] gap-2 border-b border-[#39615a] py-2.5`}><span className={method === 'POST' ? 'text-orange' : 'text-lime'}>{method}</span><b>{path}</b><small className="text-[#75ac8c]">{code}</small></div> }
function FlightRow({ time, airport, arrival, destination, price, muted }) { return <div className={`${muted ? 'opacity-40' : ''} flex items-center justify-between border-b border-[#edf1ed] py-3 font-display text-[11px]`}><span>{time}<small className="block text-[8px] text-[#8ba09b]">{airport}</small></span><Plane size={15} className="text-orange" /><span>{arrival}<small className="block text-[8px] text-[#8ba09b]">{destination}</small></span><strong>{price}</strong></div> }

export function ProductVisual({ type }) {
  if (type === 'system') return <div className="min-h-60 bg-[#e6ecdf] p-7"><div className="flex justify-between"><span className="font-display text-[9px] font-bold tracking-[.12em] text-[#80a19b]">UI / SYSTEM</span><strong className="font-display text-lg">Button</strong></div><div className="my-6 flex gap-2"><button className="bg-teal px-3 py-2 text-[10px] font-bold text-white">Primary action <ArrowRight className="ml-1 inline" size={12} /></button><button className="border border-[#a7bcb0] px-3 py-2 text-[10px] font-bold">Secondary</button></div><div className="my-6 h-px bg-[#cbd8cc]" /><div className="flex justify-between"><span className="font-display text-[9px] font-bold tracking-[.12em] text-[#80a19b]">COLOURS</span><div className="flex gap-1.5"><i className="size-[17px] bg-ink" /><i className="size-[17px] bg-teal" /><i className="size-[17px] bg-lime" /><i className="size-[17px] bg-orange" /></div></div></div>
  if (type === 'api') return <div className="min-h-60 bg-[#193936] p-7 font-display text-[11px] font-semibold text-[#d9f1df]"><ApiLine method="GET" path="/booking/seat-map" code="200" /><ApiLine method="POST" path="/booking/payment" code="201" indent /><ApiLine method="GET" path="/booking/confirmation" code="200" indent faded /><div className="mt-7 flex items-center gap-2 text-[10px] text-[#8eb2a1]"><i className="size-2 rounded-full bg-lime" />20+ workflows connected</div></div>
  return <div className="min-h-60 bg-[#c5dfdd] p-6"><div className="flex items-center gap-1.5 font-display text-[9px] font-semibold text-[#61837e]"><i className="size-1.5 rounded-full bg-[#86aaa4]" /><i className="size-1.5 rounded-full bg-[#86aaa4]" /><i className="size-1.5 rounded-full bg-[#86aaa4]" /><span className="ml-2">travel.platform / search</span></div><div className="mx-3 mt-7 bg-white p-5 shadow-lg"><span className="font-display text-[8px] font-bold tracking-[.12em] text-[#80a19b]">SEARCH FLIGHTS</span><div className="flex items-center gap-2 border-b border-[#dfe9e4] py-3 text-xs"><b>Chennai</b><ArrowRight size={14} className="text-orange" /><b>Paris</b><button className="ml-auto bg-teal p-1.5 text-white"><Search size={13} /></button></div><FlightRow time="06:10" airport="MAA" arrival="16:35" destination="CDG" price="$642" /><FlightRow time="22:45" airport="MAA" arrival="09:15" destination="CDG" price="$518" muted /></div></div>
}

export function HeroVisual() { return <div className="relative min-h-[400px] overflow-hidden bg-[#dfe9df] p-6 shadow-2xl md:min-h-[465px]"><div className="absolute -right-24 -top-24 size-64 rounded-full bg-lime" /><div className="relative flex justify-between font-display text-[10px] font-bold tracking-[.08em] text-[#52716b]"><span>BOOKING / 04</span><span>LIVE SYSTEM <b className="ml-1 inline-block size-1.5 rounded-full bg-[#62a946]" /></span></div><div className="relative mt-16 bg-ink p-7 text-white"><div className="flex justify-between font-display text-[9px] font-bold tracking-[.12em] text-[#91aaa3]"><span>ONE WAY</span><span>12 JUN 2025</span></div><div className="mt-7 flex items-center justify-between"><strong className="font-display text-4xl">MAA</strong><div className="flex items-center gap-2 text-lime"><span>✦</span><i className="block h-px w-16 bg-[#6c8982]" /><span>✈</span></div><strong className="font-display text-4xl">CDG</strong></div><div className="mt-2 flex justify-between text-[11px] text-[#9bb0a9]"><span>Chennai</span><span>Paris · 10h 25m</span></div></div><div className="flex items-center justify-between bg-white p-6"><div><span className="font-display text-[9px] font-bold tracking-[.12em] text-[#8aa19b]">YOUR SEAT</span><strong className="mt-1 block font-display text-3xl">14A</strong></div><div className="grid grid-cols-6 gap-1"><i className="size-2.5 bg-[#dae2dc]" /><i className="size-2.5 bg-[#dae2dc]" /><i className="size-2.5 bg-orange" />{Array.from({ length: 9 }, (_, i) => <i key={i} className="size-2.5 bg-[#dae2dc]" />)}</div></div><div className="absolute bottom-20 right-2 rotate-3 bg-lime p-4"><span className="block font-display text-[9px] font-bold tracking-[.1em]">PERFORMANCE</span><strong className="block font-display text-3xl">+35%</strong><small className="font-display text-[9px]">faster experience</small></div><div className="absolute bottom-5 left-6 right-6 flex justify-between font-display text-[10px] font-bold tracking-[.08em] text-[#52716b]"><span>Components / 128</span><span>Accessibility / AA</span></div></div> }
